import { Business } from "./types";

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "b1",
    name: "Café do Bairro",
    sector: "cafe",
    canton: "ZH",
    city: "Zurique",
    distanceKm: 5,
    priceMin: 180000,
    priceMax: 210000,
    establishedYear: 2014,
    photoUrl: "/businesses/cafe-do-bairro.jpg",
    sellerReadinessScore: 72,
    tags: ["Estabelecido 2014", "Financeiro Sólido"],
  },
  {
    id: "b2",
    name: "Padaria Local",
    sector: "varejo",
    canton: "BE",
    city: "Berna",
    distanceKm: 18,
    priceMin: 120000,
    priceMax: 160000,
    establishedYear: 2009,
    photoUrl: "/businesses/padaria-local.jpg",
    sellerReadinessScore: 78,
    tags: ["Clientela Fiel", "Documentação Completa"],
  },
  {
    id: "b3",
    name: "Sauna Studio",
    sector: "servicos",
    canton: "ZG",
    city: "Zug",
    distanceKm: 32,
    priceMin: 90000,
    priceMax: 130000,
    establishedYear: 2018,
    photoUrl: "/businesses/sauna-studio.jpg",
    sellerReadinessScore: 58,
    tags: ["Crescimento Recente"],
  },
  {
    id: "b4",
    name: "Loja de Flores",
    sector: "varejo",
    canton: "AG",
    city: "Aarau",
    distanceKm: 40,
    priceMin: 60000,
    priceMax: 90000,
    establishedYear: 2011,
    photoUrl: "/businesses/loja-de-flores.jpg",
    sellerReadinessScore: 45,
    tags: ["Localização Central"],
  },
  {
    id: "b5",
    name: "Restaurante Vista Lago",
    sector: "restaurante",
    canton: "VD",
    city: "Lausanne",
    distanceKm: 12,
    priceMin: 250000,
    priceMax: 320000,
    establishedYear: 2005,
    photoUrl: "/businesses/restaurante-vista-lago.jpg",
    sellerReadinessScore: 81,
    tags: ["Vista Privilegiada", "Equipa Estável"],
  },
];
